global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: connect-integration-here-location-suite
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  connect-integration-here-location-suitet1:
    parameter_input: connect-integration-here-location-suite-example-params1.json
    template_file: connect-integration-here-location-suite-example1.template
  connect-integration-here-location-suitet2:
    parameter_input: connect-integration-here-location-suite-example-params2.json
    template_file: connect-integration-here-location-suite-example2.template
